# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.
default_twitter: &default_twitter
  twitter_api_key: 'HtFrfnPsvokMFbEFqMjqRCzDx'
  twitter_api_secret: 'pTk8VLVlVZGM8iQDCgmgQd60UdTPs31ot2uAhbKN1ghFH2G685'
development:
  secret_key_base: 165d8019dd93ef8cc11a3bbb153ce6854f4978c778c4f59afe6453bd047756d03115b1e1c1c63f7554a4886563d692df8201360a3acc167da84e7950ccd5f441
  <<: *default_twitter
test:
  secret_key_base: d22f2bf7048d13f8eb67e54fac47ccd2c9f4807434488c96040b002c05aa6865be2ee1945229d5b70f2e18cae6473e7426d7ab41ebab1f0b7b8874aec6025051
  <<: *default_twitter
# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  twitter_api_key: <%= ENV["TWITTER_CONSUMER_KEY"] %>
  twitter_api_secret: <%= ENV["TWITTER_CONSUMER_SECRET"] %>
